name: Kateryna-Voznyuk-343-Lab5

on:
	workflow_dispatch:

jobs:
	logparser:
		runs-on: ubuntu-latest
		
		steps:
			- name: Checkout repository
				uses: actions/checkout@v2

			- name: Download logfile
				run: |
					wget ${secret.ACCESSLOG_URL}
				env:
					domain: ${{ secrets.DOMAIN }} # https://gitlab.com
					user: ${{ secrets.USER }} # oyakivchik
			- name: Set up Python
				uses: actions/setup-python@v2
				with:
					python-version: 3.8
			- name: Install dependencies
				run: |
					python -m pip install --upgrade pip
					if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
			- name: Get parsed data
				run: |
					python3 logparser_sql.py logfile.log
			- name: Email report
				run: |
					python send_email.py
				env:
					SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
					RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
					EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
					SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
					SMTP_PORT: ${{ secrets.SMTP_PORT }}
